from .UserSerializer import UserSerializer
from .AdministrateurSerializer import AdministrateurSerializer
from .AgentMaintenanceSerializer import AgentMaintenanceSerializer
from .MagasinierSerializer import MagasinierSerializer
from .ResponsableChaineProductionSerializer import ResponsableChaineProductionSerializer
from .ResponsableMaintenanceSerializer import ResponsableMaintenanceSerializer
from .ResponsableProductionSerializer import ResponsableProductionSerializer