# Generated by Django 4.1.2 on 2023-06-15 12:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmao_users', '0001_initial'),
        ('gmao_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bontravail',
            name='agent_maintenance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gmao_users.agentmaintenance'),
        ),
        migrations.AlterField(
            model_name='bontravail',
            name='date_liberation',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 15, 13, 38, 20, 635677), help_text='Date de liberation de l BonTravail'),
        ),
        migrations.AlterField(
            model_name='bontravail',
            name='equipement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gmao_app.equipement'),
        ),
        migrations.AlterField(
            model_name='bontravail',
            name='responsable_maintenance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gmao_users.responsablemaintenance'),
        ),
        migrations.AlterField(
            model_name='demandeintervention',
            name='date_liberation',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 15, 13, 38, 20, 635677), help_text='Date de liberation de l Demande'),
        ),
        migrations.AlterField(
            model_name='demandeintervention',
            name='equipement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gmao_app.equipement'),
        ),
        migrations.AlterField(
            model_name='demandeintervention',
            name='responsable_chaine_production',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gmao_users.responsablechaineproduction'),
        ),
        migrations.AlterField(
            model_name='demandeintervention',
            name='responsable_maintenance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gmao_users.responsablemaintenance'),
        ),
    ]
