# Generated by Django 4.1.2 on 2023-06-16 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmao_app', '0002_alter_bontravail_agent_maintenance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bontravail',
            name='date_liberation',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 16, 22, 40, 36, 466010), help_text='Date de liberation de l BonTravail', null=True),
        ),
        migrations.AlterField(
            model_name='demandeintervention',
            name='date_liberation',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 16, 22, 40, 36, 466010), help_text='Date de liberation de l Demande'),
        ),
    ]
