# Generated by Django 4.1.2 on 2023-06-20 18:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmao_users', '0001_initial'),
        ('gmao_app', '0004_alter_bontravail_date_liberation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonApprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_liberation', models.DateField(blank=True, default=datetime.date.today, help_text='date_liberation de l Bon Approvisionnement')),
                ('Description', models.TextField(blank=True, help_text='description de BonApprovisionnement', max_length=20)),
                ('magasinier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gmao_users.magasinier')),
                ('responsable_maintenance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gmao_users.responsablemaintenance')),
            ],
            options={
                'ordering': ['-date_liberation'],
            },
        ),
        migrations.AlterField(
            model_name='bontravail',
            name='date_liberation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 20, 19, 26, 2, 301783), help_text='Date de liberation de l BonTravail', null=True),
        ),
        migrations.AlterField(
            model_name='demandeintervention',
            name='date_liberation',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Date de liberation de l Demande'),
        ),
        migrations.CreateModel(
            name='PieceRechange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='code de PieceRechange', max_length=8)),
                ('nom', models.CharField(blank=True, help_text='nom de PieceRechange', max_length=125)),
                ('bon_approvisionnement', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gmao_app.bonapprovisionnement')),
            ],
            options={
                'ordering': ['-code'],
            },
        ),
    ]
