# Generated by Django 4.1.2 on 2023-06-20 18:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmao_app', '0007_alter_bonapprovisionnement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bontravail',
            name='date_liberation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 20, 19, 47, 38, 745629), help_text='Date de liberation de l BonTravail', null=True),
        ),
        migrations.AlterField(
            model_name='piecerechange',
            name='bon_approvisionnement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='piece_rechanges', to='gmao_app.bonapprovisionnement'),
        ),
    ]
