# Generated by Django 4.1.2 on 2023-06-20 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmao_app', '0009_alter_bontravail_date_liberation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bontravail',
            name='date_liberation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 20, 22, 15, 17, 176086), help_text='Date de liberation de l BonTravail', null=True),
        ),
    ]
