# Generated by Django 4.1.2 on 2023-06-20 21:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmao_app', '0010_alter_bontravail_date_liberation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bontravail',
            name='date_liberation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 20, 22, 19, 53, 764851), help_text='Date de liberation de l BonTravail', null=True),
        ),
        migrations.AlterField(
            model_name='piecerechange',
            name='bon_approvisionnement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_rechange', to='gmao_app.bonapprovisionnement'),
        ),
    ]
